# Example Site settings

header_pages:
  - index.md
  - burritoverse.md
  - sgfs.md
  - mothership.md
  - teenagers.md

footer: 'There are 69,105 leaves here.'

style: hacker # light dark (default) or light
