# Example Site settings

header_pages:
  - index.md
  - cyberpunk.md
  - mothership.md
  - teenagers.md
  - nimu.md

footer: 'There are 69,105 leaves here.'

style: hacker # light dark (default) or light
