# Example Site settings

header_pages:
  - index.md
  - cyberpunk.md
  - mothership.md

footer: ['There are 69,105 leaves here.'](https://www.pcjs.org/software/pcx86/game/infocom/zork1/)

style: hacker # light dark (default) or light
